env:
   global:
   - GCC_BASE=gcc-arm-none-eabi-6-2017-q1-update
   - GCC_SHORT=6_1-2017q1

sudo: required
language: generic
dist: trusty

addons:
  apt:
    packages:
      libc6-i386

cache:
  directories:
    - $HOME/$GCC_BASE

install:
    - export GCC_DIR=$HOME/$GCC_BASE
    - export GCC_ARCHIVE=$HOME/$GCC_BASE-linux.tar.bz2
    - export GCC_URL=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/$GCC_SHORT/$GCC_BASE-linux.tar.bz2
    - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
script:
    - mkdir -p mchf-eclipse/build-bl
    - mkdir -p mchf-eclipse/build-fw
    - mkdir -p mchf-eclipse/build-bl-f7
    - mkdir -p mchf-eclipse/build-bl-h7
    - mkdir -p mchf-eclipse/build-fw-f7
    - mkdir -p mchf-eclipse/build-fw-f4-ili9486-480
    - mkdir -p mchf-eclipse/build-fw-f4-small
    - mkdir -p mchf-eclipse/build-fw-h7
    - cd mchf-eclipse/build-fw-h7
    - cd ../build-bl-h7
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." BUILDFOR="H7" TRX_ID="ovi40" TRX_NAME="OVI40" bootloader 
    - cd ../build-fw-h7
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." BUILDFOR="H7" TRX_ID="ovi40" TRX_NAME="OVI40" all 
    - cd ../build-fw 
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." all
    - cd ../build-fw-f7
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." BUILDFOR="F7" TRX_ID="ovi40" TRX_NAME="OVI40" all
    - cd ../build-bl
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." bootloader
    - cd ../build-bl-f7
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." BUILDFOR="F7" TRX_ID="ovi40" TRX_NAME="OVI40" bootloader
    - cd ../build-fw-f4-ili9486-480
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR ROOTLOC=".." LCD_TYPE=1 all
    - cd ../build-fw-f4-small
    - make -f ../Makefile OPT_GCC_ARM=$GCC_DIR CONFIGFLAGS="-DIS_SMALL_BUILD" ROOTLOC=".." all
    - cd ..
before_deploy:
    - sudo apt-get install -y doxygen graphviz
    - make docs > /dev/null && tar -czf docs.tar.gz -C .. docs
deploy:
  provider: releases
  api_key:
    secure: "SECURE TOKEN MISSING"
  file: 
  - build-fw/fw-mchf.bin
  - build-fw-f7/fw-ovi40.bin
  - build-bl/bl-mchf.bin
  - build-bl-f7/bl-ovi40.bin
  - build-fw/fw-mchf.dfu
  - build-fw-f7/fw-ovi40.dfu
  - build-bl/bl-mchf.dfu
  - build-bl-f7/bl-ovi40.dfu
  skip_cleanup: true
  on:
    repo: sp9bsl/UHSDR
    tags: true
    branches: 
      only:
      - wip-sp9bsl-4-new-lcds
